variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - "~/unlock_ci_keychain.sh"
  - "gem update fastlane"
  - fastlane update_profiles

stages:
  - build_master
  - build_peripheral 
  - crashlytics
  - night_build

build_master_job:
  stage: build_master
  script:
    - fastlane build_application app:master scheme:appstore
  tags:
    - xcode-9

build_slave_job:
  stage: build_peripheral
  script:
    - fastlane build_application app:peripheral scheme:appstore
  tags:
    - xcode-9

crashlytics_master_job:
  stage: crashlytics
  script:
    - fastlane update_profiles
    - fastlane build_application app:master scheme:adhoc
    - fastlane upload_crashlytics app:master
  when: manual
  tags:
    - xcode-9
  environment:
    name: crashlitics


crashlytics_slave_job:
  stage: crashlytics
  script:
    - fastlane update_profiles
    - fastlane build_application app:peripheral scheme:adhoc
    - fastlane upload_crashlytics app:peripheral
  when: manual
  tags:
    - xcode-9
  environment:
    name: crashlitics

crashlytics_night_build_job:
  stage: night_build
  script:
    - fastlane update_profiles

    - fastlane build_application app:peripheral scheme:adhoc
    - fastlane upload_crashlytics app:peripheral

    - fastlane build_application app:master scheme:adhoc
    - fastlane upload_crashlytics app:master
  tags:
    - xcode-9
  environment:
    name: crashlitics
  only:
    - schedules
    - triggers